-- Initial seed data from archives/*.csv
-- Generated — do not edit by hand; rerun scripts/build_migration.py

DELETE FROM olympiads;
DELETE FROM textbooks;

INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Mathematics','November 2025','2025-11','United States','American Mathematics Competition 12',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Mathematics','October 2025','2025-10','Canada','Canadian Open Mathematics Challenge',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Mathematics','November 2024','2024-11','United States','American Mathematics Competition 12',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Mathematics','October 2024','2024-10','Canada','Canadian Open Mathematics Challenge',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','December 2026','2026-12','United States','USA North America Artificial Intelligence Olympiad',0,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','November 2026','2026-11','Canada','Canada Artificial Intelligence National Challenge',0,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','January 2026','2026-01','United States','North American Computational Linguistics Open Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','March 2025','2025-03','Canada','Canadian Computing Competition Senior Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','January 2025','2025-01','Canada','North American Computational Linguistics Open Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','January 2025','2025-01','United States','USA Computing Olympiad Bronze Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','March 2024','2024-03','Canada','Canadian Computing Competition Senior Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Computing','January 2024','2024-01','United States','USA Computing Olympiad Bronze Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','April 2026','2026-04','Canada','Canadian Association of Physicists High School Prize Exam',0,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','March 2026','2026-03','Canada','Junior Science Olympiad of Canada Exam',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','February 2026','2026-02','United States','USA Physics Olympiad F=ma Qualifying Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','November 2025','2025-11','Canada','Junior Science Olympiad of Canada National Camp - Invitation',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','May 2025','2025-05','Canada','Junior Science Olympiad of Canada Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','April 2025','2025-04','Canada','Canadian Association of Physicists High School Prize Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','February 2025','2025-02','United States','USA Physics Olympiad F=ma Qualifying Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','May 2024','2024-05','Canada','Junior Science Olympiad of Canada Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','April 2024','2024-04','Canada','Canadian Association of Physicists High School Prize Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Physics','February 2024','2024-02','United States','USA Physics Olympiad F=ma Qualifying Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','April 2026','2026-04','Canada','Canadian Chemistry Olympiad Exams',0,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','March 2026','2026-03','United States','United States National Chemistry Olympiad Local Exam',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','March 2026','2026-03','Canada','Junior Science Olympiad of Canada Exam',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','November 2025','2025-11','Canada','Junior Science Olympiad of Canada National Camp - Invitation',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','May 2025','2025-05','Canada','Junior Science Olympiad of Canada Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','April 2025','2025-04','Canada','Canadian Chemistry Olympiad Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','April 2025','2025-04','United States','United States National Chemistry Olympiad National Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','March 2025','2025-03','United States','United States National Chemistry Olympiad Local Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','May 2024','2024-05','Canada','Junior Science Olympiad of Canada Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Chemistry','April 2024','2024-04','Canada','Canadian Chemistry Olympiad Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','April 2026','2026-04','Canada','Canadian Biology Olympiad Competition Exam',0,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','March 2026','2026-03','Canada','Junior Science Olympiad of Canada Exam',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','February 2026','2026-02','United States','USA Biology Olympiad Open Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','November 2025','2025-11','Canada','Junior Science Olympiad of Canada National Camp - Invitation',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','May 2025','2025-05','Canada','Junior Science Olympiad of Canada Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','February 2025','2025-02','United States','USA Biology Olympiad Open Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','May 2024','2024-05','Canada','Junior Science Olympiad of Canada Exams',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Biology','April 2024','2024-04','Canada','Canadian Biology Olympiad Competition Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','May 2026','2026-05','Canada','Canadian Astronomy and Astrophysics Olympiad Junior Exam',0,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','March 2026','2026-03','Canada','Canadian Astronomy and Astrophysics Olympiad Senior Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','February 2026','2026-02','United States','USA Astronomy and Astrophysics Olympiad First Round Exam',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','October 2025','2025-10','Canada','International Olympiad on Astronomy and Astrophysics Junior - Invitation',0,1);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','May 2025','2025-05','Canada','Canadian Astronomy and Astrophysics Olympiad Junior Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','March 2025','2025-03','Canada','Canadian Astronomy and Astrophysics Olympiad Senior Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','February 2025','2025-02','United States','USA Astronomy and Astrophysics Olympiad First Round Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','March 2024','2024-03','Canada','Canadian Astronomy and Astrophysics Olympiad Senior Exam',1,0);
INSERT INTO olympiads (subject,date,sort_key,country,name,finished,highlighted) VALUES ('Astronomy','February 2024','2024-02','United States','USA Astronomy and Astrophysics Olympiad First Round Exam',1,0);

INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','December 2025','2025-12','Calculus: Early Transcendentals by James Stewart',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','May 2025','2025-05','Advanced Placement Calculus BC Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','May 2024','2024-05','Advanced Placement Precalculus Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','May 2024','2024-05','The Art of Problem Solving by Richard Rusczyk et al',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','September 2023','2023-09','Precalculus Mathematics in a Nutshell by George F. Simmons',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','May 2026','2026-05','Advanced Placement Statistics Exam',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','May 2025','2025-05','Advanced Placement Statistics Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','May 2025','2025-05','Advanced Placement Computer Science A Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','May 2024','2024-05','Advanced Placement Computer Science A Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','May 2024','2024-05','Advanced Placement Computer Science Principles Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2026','2026-05','Advanced Placement Physics 2 Exam',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2026','2026-05','Advanced Placement Physics C: Electricity and Magnetism Exam',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','December 2025','2025-12','Physics: Principles with Applications by Douglas C. Giancoli',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','December 2025','2025-12','Physics by Halliday, Resnick and Krane',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2025','2025-05','Advanced Placement Physics 1 Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2025','2025-05','Advanced Placement Physics 2 Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2025','2025-05','Advanced Placement Physics C: Mechanics Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2025','2025-05','Advanced Placement Physics C: Electricity and Magnetism Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2024','2024-05','University Physics by Richard Wolfson',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','May 2024','2024-05','Advanced Placement Physics 1 Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','March 2024','2024-03','Johns Hopkins University Center for Talented Youth AP Physics 1',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2026','2026-05','Advanced Placement Chemistry Exam',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','December 2025','2025-12','Chemical Principles: The Quest for Insight by Peter Atkins',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2025','2025-05','Advanced Placement Chemistry Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','April 2025','2025-04','Chemistry by Zumdahl and Zumdahl',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2024','2024-05','Advanced Placement Chemistry Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','March 2024','2024-03','Johns Hopkins University Center for Talented Youth AP Chemistry',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','May 2026','2026-05','Advanced Placement Biology Exam',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','May 2025','2025-05','Biology: A Global Approach by Neil A. Campbell',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','May 2025','2025-05','Advanced Placement Psychology Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','May 2025','2025-05','Advanced Placement Biology Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','May 2024','2024-05','Advanced Placement Biology Exam',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','March 2024','2024-03','Johns Hopkins University Center for Talented Youth AP Biology',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Astronomy','August 2024','2024-08','Fundamental Astronomy by Hannu Karttunen et al',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Astronomy','July 2024','2024-07','Everaise Academy: Astronomy by Je Qin Chooi and Gregory Pylypovych',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Astronomy','June 2024','2024-06','Fundamentals of Astronomy: A Guide for Olympiads by Flavio Salvati',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','Future','9999-12','Differential Equations with Applications and Historical Notes by George F. Simmons',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','Future','9999-12','Linear Algebra Done Right by Sheldon Axler',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','Future','9999-12','Olympiad Training for Individual Study by Evan Chen',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','Future','9999-12','The Art of Problem Solving Math Worldwide Online Olympiad Training A',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','Future','9999-12','The Art of Problem Solving Math Worldwide Online Olympiad Training B',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','June 2026','2026-06','Euclidean Geometry in Mathematical Olympiads by Evan Chen',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','June 2026','2026-06','AwesomeMath Summer Program',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','November 2025','2025-11','Athemath Women in Math Online Social Network',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','September 2025','2025-09','The Art of Problem Solving American Mathematics Competition 12 Series',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','July 2025','2025-07','MathPath Summer Camp at Mount Holyoke College',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','July 2024','2024-07','MathPath Summer Camp at Rockhurst University',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Mathematics','May 2024','2024-05','The Art of Problem Solving Book Series by Richard Rusczyk et al',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','Future','9999-12','The Art of Problem Solving Code Worldwide Online Olympiad Training',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','June 2026','2026-06','Introduction to Machine Learning by Etienne Bernard',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','June 2026','2026-06','Introduction to Machine Learning with Python by Andreas Muller and Sarah Guido',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','June 2026','2026-06','Deep Learning for Coders with fastai and PyTorch by Jeremy Howard and Sylvain Gugger',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','June 2026','2026-06','Machine Learning with PyTorch and Scikit-Learn by Sebastian Raschka',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','June 2026','2026-06','Grokking Machine Learning by Luis Serrano',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','January 2026','2026-01','Puzzles in Logic, Languages and Computation: the Red book by Dragomir Radev',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','January 2026','2026-01','Puzzles in Logic, Languages and Computation: the Green book by Dragomir Radev',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','December 2025','2025-12','Linguistics Olympiad: Training Guide - the Yellow book by Vlad A. Neacsu',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Computing','January 2025','2025-01','The Art of Problem Solving USACO Bronze Series',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','Future','9999-12','The Feynman Lectures on Physics by Richard Feynman',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','Future','9999-12','The Art of Problem Solving Physics Worldwide Online Olympiad Training A',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','Future','9999-12','The Art of Problem Solving Physics Worldwide Online Olympiad Training B',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','December 2025','2025-12','Physics Olympiad Handouts by Kevin Zhou',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Physics','March 2025','2025-03','The Art of Problem Solving Physics F=ma Series',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','January 2027','2027-01','Chemistry 342 Organic Chemistry B Organic Chemistry by Paula Yurkanis Bruice',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','September 2026','2026-09','Chemistry 341 Organic Chemistry A Organic Chemistry by Paula Yurkanis Bruice',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2026','2026-05','British Columbia Chemistry Olympiad',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2026','2026-05','Atkins'' Physical Chemistry by Peter Atkins, Julio de Paula and James Keeler',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2026','2026-05','Organic Chemistry by Jonathan Clayden, Nick Greeves and Stuart Warren',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2026','2026-05','Inorganic Chemistry by Mark Weller, Jonathan Rourke, Fraser Armstrong and Tina Overton',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','April 2026','2026-04','Canadian Chemistry Olympiad Training Course by Ivan Shershnev',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','March 2026','2026-03','Descriptive Inorganic, Coordination, and Solid State Chemistry by Glen E. Rodgers',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','February 2026','2026-02','Organic Chemistry as a Second Language by David Klein',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','January 2026','2026-01','The Art of Problem Solving Chemistry Worldwide Online Olympiad Training B',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','January 2026','2026-01','The Art of Problem Solving Chemistry Worldwide Online Olympiad Training A',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2025','2025-05','British Columbia Chemistry Olympiad',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','April 2025','2025-04','Washington University Chemistry Tournament',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','March 2025','2025-03','University of California Berkeley Chemistry Tournament',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Chemistry','May 2024','2024-05','British Columbia Chemistry Olympiad',1,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','Future','9999-12','The USA Biology Olympiad Semifinal Exams Worked Solutions by Martyna Petrulyte',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Biology','March 2024','2024-03','The USA Biology Olympiad Open Exam Exams Worked Solutions by Martyna Petrulyte',0,1);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Astronomy','January 2027','2027-01','Astronomy 410 Astrophysics Astrophysics in a Nutshell by Dan Maoz',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Astronomy','September 2026','2026-09','Astronomy 310 Astrophysics Measurements To Measure the Sky by Frederick R. Chromey',0,0);
INSERT INTO textbooks (subject,date,sort_key,title,finished,highlighted) VALUES ('Astronomy','March 2026','2026-03','Foundations of Astrophysics by Barbara Ryden and Bradley Peterson',0,1);
